import "NiMPC/testCommunication"
import "NiMPC/testMath"
import "NiMPC/testObliviousTransfer"
import "NiMPC/ObliviousTransfer/testOTCommunication"
import "NiMPC/ObliviousTransfer/testOTSequence"
import "NiMPC/Parties/testIdentity"
import "NiMPC/Parties/testLocalParties"
import "NiMPC/Parties/testPartyConnections"
import "NiMPC/Parties/testRemoteParties"
import "NiMPC/Parties/testListener"
import "NiMPC/Parties/testEnvelopes"
import "NiMPC/Parties/testCheckEnvelope"
import "NiMPC/Parties/testHexString"
import "NiMPC/testLocalRandom"
import "NiMPC/testRandom"
import "NiMPC/testSecretSharing"
import "NiMPC/SecretSharing/testSecretInternals"
import "NiMPC/testTriples"
import "NiMPC/Triples/testTripleCommunication"
import "NiMPC/Triples/testTripleConversion"
import "NiMPC/Triples/testTripleMath"
import "NiMPC/testExample"

{.warning[UnusedImport]:off.}
