import "NiMPC/testCommunication"
import "NiMPC/testMath"
import "NiMPC/testObliviousTransfer"
import "NiMPC/ObliviousTransfer/testOTCommunication"
import "NiMPC/ObliviousTransfer/testOTSequence"
import "NiMPC/testParties"
import "NiMPC/Parties/testRemoteParties"
import "NiMPC/testLocalRandom"
import "NiMPC/testRandom"
import "NiMPC/testSecretSharing"
import "NiMPC/SecretSharing/testSecretInternals"
import "NiMPC/testTriples"
import "NiMPC/Triples/testTripleCommunication"
import "NiMPC/Triples/testTripleConversion"
import "NiMPC/Triples/testTripleMath"
import "NiMPC/testExample"

{.warning[UnusedImport]:off.}
